[package]
name = "RustApi"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde-xml-rs = "0.6"
log = "0.4.26"
env_logger = "0.11.6"
